name: monitor
description: "A flutter package to monitor HTTP API Requests."
version: 1.3.0
repository: https://github.com/amaan-0331/monitor

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
